# Generated by Django 5.2.6 on 2025-09-25 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_message_templates(apps, schema_editor):
    MessageTemplate = apps.get_model("chats", "MessageTemplate")
    defaults = [
        {
            "key": "running-late",
            "label": "Running late",
            "body": "I'm running a few minutes behind schedule but am on my way.",
            "audience": "universal",
        },
        {
            "key": "ingredients-substitution",
            "label": "Ingredient substitution",
            "body": "I'm missing an ingredient. Can we substitute with the suggested alternative?",
            "audience": "client",
        },
        {
            "key": "order-picked-up",
            "label": "Order picked up",
            "body": "Order has been picked up and is en route to the client.",
            "audience": "dispatch",
        },
        {
            "key": "ready-for-pickup",
            "label": "Ready for pickup",
            "body": "Meal prep is complete and ready for dispatch pickup.",
            "audience": "dispatch",
        },
    ]

    for template in defaults:
        MessageTemplate.objects.get_or_create(key=template["key"], defaults=template)


def remove_default_message_templates(apps, schema_editor):
    MessageTemplate = apps.get_model("chats", "MessageTemplate")
    MessageTemplate.objects.filter(
        key__in=[
            "running-late",
            "ingredients-substitution",
            "order-picked-up",
            "ready-for-pickup",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
        ("orders", "0003_alter_cart_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("chef", "Chef"),
                            ("dispatch", "Dispatch"),
                            ("universal", "All Participants"),
                        ],
                        default="universal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="OrderChatThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_thread",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_order_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="chats.messagetemplate",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.orderchatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("chef", "Chef"),
                            ("dispatch", "Dispatch"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_participants",
                        to="chats.orderchatthread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("thread", "user")},
            },
        ),
        migrations.AddField(
            model_name="orderchatthread",
            name="participants",
            field=models.ManyToManyField(
                related_name="order_chat_threads",
                through="chats.ThreadParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(create_default_message_templates, remove_default_message_templates),
    ]
