# Generated by Django 5.2.6 on 2025-09-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("orders", "0002_alter_order_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="clients.client",
            ),
        ),
    ]
