# Generated by Django 5.2.6 on 2025-09-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("orders", "0003_alter_cart_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAllergenReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_allergy_notes", models.TextField(blank=True)),
                ("reported_by_client", models.BooleanField(default=False)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by_chef", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement_notes", models.TextField(blank=True)),
                ("allergies", models.ManyToManyField(blank=True, to="clients.allergy")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergen_report",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order allergen report",
                "verbose_name_plural": "Order allergen reports",
            },
        ),
    ]
