# Generated by Django 5.2.6 on 2025-09-25 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low Risk"),
                            ("Medium", "Medium Risk"),
                            ("High", "High Risk"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="allergy_icons/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietaryPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="dietary_icons/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dietary_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Vegetarian", "Vegetarian"),
                            ("Vegan", "Vegan"),
                            ("Keto", "Keto"),
                            ("Gluten Free", "Gluten-Free"),
                            ("Halal", "Halal"),
                            ("Kosher", "Kosher"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "passport_id_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Busy Professional", "Busy Professional"),
                            ("Fitness Health", "Fitness & Health Enthusiast"),
                            ("Family Meal Planner", "Family Meal Planner"),
                            ("Student", "Student"),
                            ("Food Lover", "Foodie/Culinary Explorer"),
                            ("Dietary Specific", "Special Dietary Needs"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allergies", models.ManyToManyField(blank=True, to="clients.allergy")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dietary_preferences",
                    models.ManyToManyField(blank=True, to="clients.dietarypreference"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientHomeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "digital_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients_locations",
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
