# Generated by Django 5.2.6 on 2025-09-25 09:04

import chef.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("food", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="chef_certifications/"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CuisineSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="cuisine_icons/"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChefProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chef_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "chef_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Home Chef", "Home Chef"),
                            ("Professional Chef", "Professional Chef"),
                            ("Culinary Student", "Culinary Student"),
                            ("Hobby Cook", "Hobby Cook"),
                            ("Catering Professional", "Catering Professional"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("kitchen_address", models.TextField(blank=True, null=True)),
                (
                    "kitchen_location",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=20,
                        default=0.0,
                        max_digits=50,
                        null=True,
                    ),
                ),
                ("service_radius", models.IntegerField(default=10)),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                            ("Both", "Both"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("max_order_capacity", models.IntegerField(default=10)),
                ("total_orders", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0)),
                ("active", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certifications",
                    models.ManyToManyField(blank=True, to="chef.certification"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuisine_specialties",
                    models.ManyToManyField(blank=True, to="chef.cuisinespecialty"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChefGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="chef/gallery/"),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chef.chefprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChefDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity"),
                            ("certification", "Certification"),
                            ("kitchen", "Kitchen"),
                        ],
                        max_length=32,
                    ),
                ),
                ("file", models.FileField(upload_to=chef.models.chef_document_upload)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="chef.chefprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ChefDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "small_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "small_value",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "medium_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "medium_value",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "large_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "large_value",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                (
                    "grocery_budget_estimate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("menu_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_chefs",
                        to="food.dish",
                    ),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chef_dishes",
                        to="chef.chefprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChefReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.CharField(blank=True, max_length=200, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints_complaints",
                        to="chef.chefprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="chef.chefdish",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("menu_item", "version")},
            },
        ),
    ]
