# Generated by Django 5.2.6 on 2025-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="consent_source",
            field=models.CharField(default="app", max_length=100),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="consent_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="consent_version",
            field=models.CharField(default="2024-09", max_length=50),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="marketing_updates",
            field=models.BooleanField(default=False),
        ),
    ]
